name = "Karpuz Pack 1.20.1"
author = "Karpuz Network"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f9dc3f363f468ebd2dba8a412125df51f04e73f637fe35eef831c3a20a731f7"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
