name = "Karpuz Pack 1.20.1"
author = "Karpuz Network"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9185cbb2c95f8210f0bef394349b6ad140ceb5ca641c7c34baf2f5e47f11e731"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
